In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df1 = pd.read_csv('/content/drive/MyDrive/IronHack/Data Analysis/Bootcamp/Proyecto Final/Datasets Base/Banking_Crisis_Dummies.csv')
df2 = pd.read_csv('/content/drive/MyDrive/IronHack/Data Analysis/Bootcamp/Proyecto Final/Datasets Base/Macroeconomic_Indicators.csv')

In [ ]:
df1.head()

                                       Series Name  ... 2017 [YR2017]
0  Banking crisis dummy (1=banking crisis, 0=none)  ...           0.0
1  Banking crisis dummy (1=banking crisis, 0=none)  ...           0.0
2  Banking crisis dummy (1=banking crisis, 0=none)  ...           0.0
3  Banking crisis dummy (1=banking crisis, 0=none)  ...           0.0
4  Banking crisis dummy (1=banking crisis, 0=none)  ...           0.0

[5 rows x 16 columns]

In [ ]:
df2.head()

  Country Name Country Code  ...     2019 [YR2019]     2020 [YR2020]
0    Argentina          ARG  ...  15.7963628519449  17.8537791737235
1    Argentina          ARG  ...  422995834686.456  358374943437.124
2    Argentina          ARG  ...  445445177459.453   383066977653.56
3    Argentina          ARG  ...  9912.28180859863   8441.9194391094
4    Argentina          ARG  ...        2983330000        2183040000

[5 rows x 35 columns]

In [ ]:
df2[df2['Country Name'] == 'Afghanistan']

    Country Name Country Code  ...      2019 [YR2019]      2020 [YR2020]
520  Afghanistan          AFG  ...                 ..                 ..
521  Afghanistan          AFG  ...                 ..                 ..
522  Afghanistan          AFG  ...   19291104007.6135   19807067268.1084
523  Afghanistan          AFG  ...   507.103391875763   508.808409485223
524  Afghanistan          AFG  ...                 ..                 ..
525  Afghanistan          AFG  ...   490.232314247094                 ..
526  Afghanistan          AFG  ...                 ..                 ..
527  Afghanistan          AFG  ...  -3791935256.04003  -3136120114.98308
528  Afghanistan          AFG  ...                 ..                 ..
529  Afghanistan          AFG  ...                 ..                 ..
530  Afghanistan          AFG  ...   26321046.5766518   37228478.0954418
531  Afghanistan          AFG  ...                 ..                 ..
532  Afghanistan          AFG  ...   2711965078.76083   2470117699.32256
533  Afghanistan          AFG  ...           85000000                 ..
534  Afghanistan          AFG  ...                 ..                 ..
535  Afghanistan          AFG  ...   828571904.111179    788917115.24523
536  Afghanistan          AFG  ...   217292317.990937   225420606.479917
537  Afghanistan          AFG  ...                  0                  0
538  Afghanistan          AFG  ...                 ..                 ..
539  Afghanistan          AFG  ...  -14623495.6263984   63243241.2445809
540  Afghanistan          AFG  ...                 ..                 ..
541  Afghanistan          AFG  ...   651924336.418389    699571419.59346
542  Afghanistan          AFG  ...    1212787550.7108   1103490351.71454
543  Afghanistan          AFG  ...   8497655795.34729   9694989380.62795
544  Afghanistan          AFG  ...   7426979265.63529   8365531057.72955
545  Afghanistan          AFG  ...        276923268.4                 ..

[26 rows x 35 columns]

In [ ]:
col_names = df2['Series Name'].unique()
col_names.tolist()

['Gross savings (% of GDP)',
 'Gross national expenditure (current US$)',
 'GDP (current US$)',
 'GDP per capita (current US$)',
 'Stocks traded, total value (current US$)',
 'Adjusted net national income per capita (current US$)',
 'Changes in inventories (current US$)',
 'Current account balance (BoP, current US$)',
 'Exports of goods and services (current US$)',
 'External balance on goods and services (current US$)',
 'Foreign direct investment, net outflows (BoP, current US$)',
 'Imports of goods and services (current US$)',
 'Industry (including construction), value added (current US$)',
 'International tourism, receipts (current US$)',
 'Market capitalization of listed domestic companies (current US$)',
 'Personal remittances, received (current US$)',
 'Personal remittances, paid (current US$)',
 'Portfolio equity, net inflows (BoP, current US$)',
 'Portfolio investment, bonds (PPG + PNG) (NFL, current US$)',
 'Portfolio investment, net (BoP, current US$)',
 'Pump price for gasoline (US$ per liter)',
 'Service exports (BoP, current US$)',
 'Service imports (BoP, current US$)',
 'Total reserves (includes gold, current US$)',
 'Total reserves minus gold (current US$)',
 'Use of IMF credit (DOD, current US$)',
 nan]

In [ ]:
len(col_names)

27

In [ ]:
data = df2.merge(df1, on='Country Name')
data.head()

  Country Name Country Code_x  ... 2016 [YR2016]_y 2017 [YR2017]_y
0    Argentina            ARG  ...             0.0             0.0
1    Argentina            ARG  ...             0.0             0.0
2    Argentina            ARG  ...             0.0             0.0
3    Argentina            ARG  ...             0.0             0.0
4    Argentina            ARG  ...             0.0             0.0

[5 rows x 50 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5475 entries, 0 to 5474
Data columns (total 50 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Country Name     5460 non-null   object
 1   Country Code_x   5460 non-null   object
 2   Series Name_x    5460 non-null   object
 3   Series Code_x    5460 non-null   object
 4   1990 [YR1990]_x  5460 non-null   object
 5   1991 [YR1991]    5460 non-null   object
 6   1992 [YR1992]    5460 non-null   object
 7   1993 [YR1993]    5460 non-null   object
 8   1994 [YR1994]    5460 non-null   object
 9   1995 [YR1995]    5460 non-null   object
 10  1996 [YR1996]    5460 non-null   object
 11  1997 [YR1997]    5460 non-null   object
 12  1998 [YR1998]    5460 non-null   object
 13  1999 [YR1999]    5460 non-null   object
 14  2000 [YR2000]_x  5460 non-null   object
 15  2001 [YR2001]    5460 non-null   object
 16  2002 [YR2002]    5460 non-null   object
 17  2003 [YR2003]    5460 non-null   object
 18  2004 [YR2004]    5460 non-null   object
 19  2005 [YR2005]    5460 non-null   object
 20  2006 [YR2006]    5460 non-null   object
 21  2007 [YR2007]    5460 non-null   object
 22  2008 [YR2008]_x  5460 non-null   object
 23  2009 [YR2009]_x  5460 non-null   object
 24  2010 [YR2010]_x  5460 non-null   object
 25  2011 [YR2011]_x  5460 non-null   object
 26  2012 [YR2012]_x  5460 non-null   object
 27  2013 [YR2013]_x  5460 non-null   object
 28  2014 [YR2014]_x  5460 non-null   object
 29  2015 [YR2015]_x  5460 non-null   object
 30  2016 [YR2016]_x  5460 non-null   object
 31  2017 [YR2017]_x  5460 non-null   object
 32  2018 [YR2018]    5460 non-null   object
 33  2019 [YR2019]    5460 non-null   object
 34  2020 [YR2020]    5460 non-null   object
 35  Series Name_y    5466 non-null   object
 36  Series Code_y    5460 non-null   object
 37  Country Code_y   5460 non-null   object
 38  1990 [YR1990]_y  5460 non-null   float64
 39  2000 [YR2000]_y  5460 non-null   float64
 40  2008 [YR2008]_y  5460 non-null   float64
 41  2009 [YR2009]_y  5460 non-null   float64
 42  2010 [YR2010]_y  5460 non-null   float64
 43  2011 [YR2011]_y  5460 non-null   float64
 44  2012 [YR2012]_y  5460 non-null   float64
 45  2013 [YR2013]_y  5460 non-null   float64
 46  2014 [YR2014]_y  5460 non-null   float64
 47  2015 [YR2015]_y  5460 non-null   float64
 48  2016 [YR2016]_y  5460 non-null   float64
 49  2017 [YR2017]_y  5460 non-null   float64
dtypes: float64(12), object(38)
memory usage: 2.1+ MB

In [ ]:
data.drop(['Series Name_y','Series Code_y','Country Code_y'], inplace=True, axis=1)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5475 entries, 0 to 5474
Data columns (total 47 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Country Name     5460 non-null   object
 1   Country Code_x   5460 non-null   object
 2   Series Name_x    5460 non-null   object
 3   Series Code_x    5460 non-null   object
 4   1990 [YR1990]_x  5460 non-null   object
 5   1991 [YR1991]    5460 non-null   object
 6   1992 [YR1992]    5460 non-null   object
 7   1993 [YR1993]    5460 non-null   object
 8   1994 [YR1994]    5460 non-null   object
 9   1995 [YR1995]    5460 non-null   object
 10  1996 [YR1996]    5460 non-null   object
 11  1997 [YR1997]    5460 non-null   object
 12  1998 [YR1998]    5460 non-null   object
 13  1999 [YR1999]    5460 non-null   object
 14  2000 [YR2000]_x  5460 non-null   object
 15  2001 [YR2001]    5460 non-null   object
 16  2002 [YR2002]    5460 non-null   object
 17  2003 [YR2003]    5460 non-null   object
 18  2004 [YR2004]    5460 non-null   object
 19  2005 [YR2005]    5460 non-null   object
 20  2006 [YR2006]    5460 non-null   object
 21  2007 [YR2007]    5460 non-null   object
 22  2008 [YR2008]_x  5460 non-null   object
 23  2009 [YR2009]_x  5460 non-null   object
 24  2010 [YR2010]_x  5460 non-null   object
 25  2011 [YR2011]_x  5460 non-null   object
 26  2012 [YR2012]_x  5460 non-null   object
 27  2013 [YR2013]_x  5460 non-null   object
 28  2014 [YR2014]_x  5460 non-null   object
 29  2015 [YR2015]_x  5460 non-null   object
 30  2016 [YR2016]_x  5460 non-null   object
 31  2017 [YR2017]_x  5460 non-null   object
 32  2018 [YR2018]    5460 non-null   object
 33  2019 [YR2019]    5460 non-null   object
 34  2020 [YR2020]    5460 non-null   object
 35  1990 [YR1990]_y  5460 non-null   float64
 36  2000 [YR2000]_y  5460 non-null   float64
 37  2008 [YR2008]_y  5460 non-null   float64
 38  2009 [YR2009]_y  5460 non-null   float64
 39  2010 [YR2010]_y  5460 non-null   float64
 40  2011 [YR2011]_y  5460 non-null   float64
 41  2012 [YR2012]_y  5460 non-null   float64
 42  2013 [YR2013]_y  5460 non-null   float64
 43  2014 [YR2014]_y  5460 non-null   float64
 44  2015 [YR2015]_y  5460 non-null   float64
 45  2016 [YR2016]_y  5460 non-null   float64
 46  2017 [YR2017]_y  5460 non-null   float64
dtypes: float64(12), object(35)
memory usage: 2.0+ MB

In [ ]:
data.head()

  Country Name Country Code_x  ... 2016 [YR2016]_y 2017 [YR2017]_y
0    Argentina            ARG  ...             0.0             0.0
1    Argentina            ARG  ...             0.0             0.0
2    Argentina            ARG  ...             0.0             0.0
3    Argentina            ARG  ...             0.0             0.0
4    Argentina            ARG  ...             0.0             0.0

[5 rows x 47 columns]

In [ ]:
data.isnull()

      Country Name  Country Code_x  ...  2016 [YR2016]_y  2017 [YR2017]_y
0            False           False  ...            False            False
1            False           False  ...            False            False
2            False           False  ...            False            False
3            False           False  ...            False            False
4            False           False  ...            False            False
...            ...             ...  ...              ...              ...
5470          True            True  ...             True             True
5471          True            True  ...             True             True
5472          True            True  ...             True             True
5473          True            True  ...             True             True
5474          True            True  ...             True             True

[5475 rows x 47 columns]

In [ ]:
data.isnull().sum()

Country Name       15
Country Code_x     15
Series Name_x      15
Series Code_x      15
1990 [YR1990]_x    15
1991 [YR1991]      15
1992 [YR1992]      15
1993 [YR1993]      15
1994 [YR1994]      15
1995 [YR1995]      15
1996 [YR1996]      15
1997 [YR1997]      15
1998 [YR1998]      15
1999 [YR1999]      15
2000 [YR2000]_x    15
2001 [YR2001]      15
2002 [YR2002]      15
2003 [YR2003]      15
2004 [YR2004]      15
2005 [YR2005]      15
2006 [YR2006]      15
2007 [YR2007]      15
2008 [YR2008]_x    15
2009 [YR2009]_x    15
2010 [YR2010]_x    15
2011 [YR2011]_x    15
2012 [YR2012]_x    15
2013 [YR2013]_x    15
2014 [YR2014]_x    15
2015 [YR2015]_x    15
2016 [YR2016]_x    15
2017 [YR2017]_x    15
2018 [YR2018]      15
2019 [YR2019]      15
2020 [YR2020]      15
1990 [YR1990]_y    15
2000 [YR2000]_y    15
2008 [YR2008]_y    15
2009 [YR2009]_y    15
2010 [YR2010]_y    15
2011 [YR2011]_y    15
2012 [YR2012]_y    15
2013 [YR2013]_y    15
2014 [YR2014]_y    15
2015 [YR2015]_y    15
2016 [YR2016]_y    15
2017 [YR2017]_y    15
dtype: int64

In [ ]:
data.dropna(axis=0, inplace=True)

In [ ]:
data.isnull().sum()

Country Name       0
Country Code_x     0
Series Name_x      0
Series Code_x      0
1990 [YR1990]_x    0
1991 [YR1991]      0
1992 [YR1992]      0
1993 [YR1993]      0
1994 [YR1994]      0
1995 [YR1995]      0
1996 [YR1996]      0
1997 [YR1997]      0
1998 [YR1998]      0
1999 [YR1999]      0
2000 [YR2000]_x    0
2001 [YR2001]      0
2002 [YR2002]      0
2003 [YR2003]      0
2004 [YR2004]      0
2005 [YR2005]      0
2006 [YR2006]      0
2007 [YR2007]      0
2008 [YR2008]_x    0
2009 [YR2009]_x    0
2010 [YR2010]_x    0
2011 [YR2011]_x    0
2012 [YR2012]_x    0
2013 [YR2013]_x    0
2014 [YR2014]_x    0
2015 [YR2015]_x    0
2016 [YR2016]_x    0
2017 [YR2017]_x    0
2018 [YR2018]      0
2019 [YR2019]      0
2020 [YR2020]      0
1990 [YR1990]_y    0
2000 [YR2000]_y    0
2008 [YR2008]_y    0
2009 [YR2009]_y    0
2010 [YR2010]_y    0
2011 [YR2011]_y    0
2012 [YR2012]_y    0
2013 [YR2013]_y    0
2014 [YR2014]_y    0
2015 [YR2015]_y    0
2016 [YR2016]_y    0
2017 [YR2017]_y    0
dtype: int64

In [ ]:
data['Series Code_x']

0       NY.GNS.ICTR.ZS
1       NE.DAB.TOTL.CD
2       NY.GDP.MKTP.CD
3       NY.GDP.PCAP.CD
4       CM.MKT.TRAD.CD
             ...
5455    BX.GSR.NFSV.CD
5456    BM.GSR.NFSV.CD
5457    FI.RES.TOTL.CD
5458    FI.RES.XGLD.CD
5459    DT.DOD.DIMF.CD
Name: Series Code_x, Length: 5460, dtype: object

In [ ]:
data.drop(['Series Code_x'],axis=1, inplace=True)

In [ ]:
data.columns = data.columns.str.replace(r"\D+","")
data.head()

                   ... 20162016 20172017
0  Argentina  ARG  ...      0.0      0.0
1  Argentina  ARG  ...      0.0      0.0
2  Argentina  ARG  ...      0.0      0.0
3  Argentina  ARG  ...      0.0      0.0
4  Argentina  ARG  ...      0.0      0.0

[5 rows x 46 columns]

In [ ]:
data.columns = ['Country name','Country code','Indicator','1990',"1991","1992","1993","1994","1995","1996","1997","1998","1999","2000","2001","2002","2003","2004","2005","2006",
                         "2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","1990 target","2000 target","2008 target","2009 target","2010 target","2011 target","2012 target",
                "2013 target","2014 target","2015 target","2016 target","2017 target"]

In [ ]:
data.head()

  Country name Country code  ... 2016 target 2017 target
0    Argentina          ARG  ...         0.0         0.0
1    Argentina          ARG  ...         0.0         0.0
2    Argentina          ARG  ...         0.0         0.0
3    Argentina          ARG  ...         0.0         0.0
4    Argentina          ARG  ...         0.0         0.0

[5 rows x 46 columns]

In [ ]:
data.drop(['Country code'],axis=1, inplace=True)

In [ ]:
# data = data.transpose()
# data = data.set_index(['Country name','Country code']).T

data.head()

  Country name  ... 2017 target
0    Argentina  ...         0.0
1    Argentina  ...         0.0
2    Argentina  ...         0.0
3    Argentina  ...         0.0
4    Argentina  ...         0.0

[5 rows x 45 columns]

In [ ]:
df = data.set_index('Country name')
df.transpose()

Country name                 Argentina  ...                              Zimbabwe
Indicator     Gross savings (% of GDP)  ...  Use of IMF credit (DOD, current US$)
1990                  16.0433766574382  ...                               6891365
1991                  13.5618560304189  ...                                     0
1992                  13.6516281676646  ...                             216150000
1993                  16.2505279122602  ...                           281579790.1
1994                  15.6483624533872  ...                           375911363.1
1995                  16.5116322700598  ...                           460811903.5
1996                  17.1300773563084  ...                           437236192.1
1997                  16.6642824266429  ...                           385255388.6
1998                  16.1297343275958  ...                           407171308.9
1999                  13.6619163753345  ...                           382930278.3
2000                  14.3684376958258  ...                           293949525.1
2001                  14.2140728227831  ...                           274770190.4
2002                  21.3431768782392  ...                           294113118.7
2003                  21.7345330075457  ...                             316710730
2004                  13.7828348747865  ...                             309047437
2005                  13.7086097328953  ...                           125085422.6
2006                  21.3902143492892  ...                           128123730.4
2007                  22.2111475246564  ...                             134460312
2008                  21.1014580679688  ...                           129425807.6
2009                  18.2953229616244  ...                           542317089.1
2010                  17.3052805596303  ...                           528729079.6
2011                  17.3484303943707  ...                           527094857.9
2012                  16.0551647849633  ...                           520124286.6
2013                  14.9543621104664  ...                             519341900
2014                   15.752009923961  ...                           486727497.2
2015                  14.1426047002076  ...                           463752752.4
2016                  14.6381195257706  ...                           455165191.5
2017                  13.0762522929971  ...                           482184792.8
2018                  14.4241190515684  ...                           470895600.2
2019                  15.7963628519449  ...                           468198468.7
2020                  17.8537791737235  ...                                    ..
1990 target                          1  ...                                     0
2000 target                          0  ...                                     0
2008 target                          0  ...                                     0
2009 target                          0  ...                                     0
2010 target                          0  ...                                     0
2011 target                          0  ...                                     0
2012 target                          0  ...                                     0
2013 target                          0  ...                                     0
2014 target                          0  ...                                     0
2015 target                          0  ...                                     0
2016 target                          0  ...                                     0
2017 target                          0  ...                                     0

[44 rows x 5460 columns]

In [ ]:
data.head()

  Country name  ... 2017 target
0    Argentina  ...         0.0
1    Argentina  ...         0.0
2    Argentina  ...         0.0
3    Argentina  ...         0.0
4    Argentina  ...         0.0

[5 rows x 45 columns]

In [ ]:
data = data.set_index('Indicator').T

In [ ]:
data

Indicator    Gross savings (% of GDP)  ... Use of IMF credit (DOD, current US$)
Country name                Argentina  ...                             Zimbabwe
1990                 16.0433766574382  ...                              6891365
1991                 13.5618560304189  ...                                    0
1992                 13.6516281676646  ...                            216150000
1993                 16.2505279122602  ...                          281579790.1
1994                 15.6483624533872  ...                          375911363.1
1995                 16.5116322700598  ...                          460811903.5
1996                 17.1300773563084  ...                          437236192.1
1997                 16.6642824266429  ...                          385255388.6
1998                 16.1297343275958  ...                          407171308.9
1999                 13.6619163753345  ...                          382930278.3
2000                 14.3684376958258  ...                          293949525.1
2001                 14.2140728227831  ...                          274770190.4
2002                 21.3431768782392  ...                          294113118.7
2003                 21.7345330075457  ...                            316710730
2004                 13.7828348747865  ...                            309047437
2005                 13.7086097328953  ...                          125085422.6
2006                 21.3902143492892  ...                          128123730.4
2007                 22.2111475246564  ...                            134460312
2008                 21.1014580679688  ...                          129425807.6
2009                 18.2953229616244  ...                          542317089.1
2010                 17.3052805596303  ...                          528729079.6
2011                 17.3484303943707  ...                          527094857.9
2012                 16.0551647849633  ...                          520124286.6
2013                 14.9543621104664  ...                            519341900
2014                  15.752009923961  ...                          486727497.2
2015                 14.1426047002076  ...                          463752752.4
2016                 14.6381195257706  ...                          455165191.5
2017                 13.0762522929971  ...                          482184792.8
2018                 14.4241190515684  ...                          470895600.2
2019                 15.7963628519449  ...                          468198468.7
2020                 17.8537791737235  ...                                   ..
1990 target                         1  ...                                    0
2000 target                         0  ...                                    0
2008 target                         0  ...                                    0
2009 target                         0  ...                                    0
2010 target                         0  ...                                    0
2011 target                         0  ...                                    0
2012 target                         0  ...                                    0
2013 target                         0  ...                                    0
2014 target                         0  ...                                    0
2015 target                         0  ...                                    0
2016 target                         0  ...                                    0
2017 target                         0  ...                                    0

[44 rows x 5460 columns]

In [ ]:
data.head()

Indicator    Gross savings (% of GDP)  ... Use of IMF credit (DOD, current US$)
Country name                Argentina  ...                             Zimbabwe
1990                 16.0433766574382  ...                              6891365
1991                 13.5618560304189  ...                                    0
1992                 13.6516281676646  ...                            216150000
1993                 16.2505279122602  ...                          281579790.1

[5 rows x 5460 columns]

In [ ]:
df = data.transpose().reset_index()
countries = df['Country name']

In [ ]:
dummies = df[['Country name',"1990 target","2000 target","2008 target","2009 target","2010 target","2011 target","2012 target",
                "2013 target","2014 target","2015 target","2016 target","2017 target"]]

In [ ]:
dummies

     Country name 1990 target 2000 target  ... 2015 target 2016 target 2017 target
0       Argentina           1           0  ...           0           0           0
1       Argentina           1           0  ...           0           0           0
2       Argentina           1           0  ...           0           0           0
3       Argentina           1           0  ...           0           0           0
4       Argentina           1           0  ...           0           0           0
...           ...         ...         ...  ...         ...         ...         ...
5455     Zimbabwe           0           0  ...           0           0           0
5456     Zimbabwe           0           0  ...           0           0           0
5457     Zimbabwe           0           0  ...           0           0           0
5458     Zimbabwe           0           0  ...           0           0           0
5459     Zimbabwe           0           0  ...           0           0           0

[5460 rows x 13 columns]

In [ ]:
data = data.iloc[0:]
data.head()

Indicator    Gross savings (% of GDP)  ... Use of IMF credit (DOD, current US$)
Country name                Argentina  ...                             Zimbabwe
1990                 16.0433766574382  ...                              6891365
1991                 13.5618560304189  ...                                    0
1992                 13.6516281676646  ...                            216150000
1993                 16.2505279122602  ...                          281579790.1

[5 rows x 5460 columns]

In [ ]:
years = data.iloc[:-12]
years.columns = range(years.shape[1])
years

                          0                 1     ...              5458         5459
Country name         Argentina         Argentina  ...          Zimbabwe     Zimbabwe
1990          16.0433766574382  133255399128.802  ...  149202984.592622      6891365
1991          13.5618560304189   186690084740.43  ...  149684564.648329            0
1992          13.6516281676646  232299611952.352  ...  222181251.804694    216150000
1993          16.2505279122602  242434054654.655  ...  432043634.668391  281579790.1
1994          15.6483624533872      265354819300  ...    405275753.9748  375911363.1
1995          16.5116322700598      259091370000  ...  595516728.603537  460811903.5
1996          17.1300773563084      273916757800  ...  598812382.519067  437236192.1
1997          16.6642824266429      299344177400  ...  160096552.663961  385255388.6
1998          16.1297343275958      306478458500  ...  130759646.726695  407171308.9
1999          13.6619163753345      288423424000  ...  267960302.144825  382930278.3
2000          14.3684376958258      286050194900  ...  193133708.310207  293949525.1
2001          14.2140728227831      265188172200  ...  64712329.2732583  274770190.4
2002          21.3431768782392  83053262771.2124  ...  83357907.8025755  294113118.7
2003          21.7345330075457  113275319790.924  ...  85187539.3967853    316710730
2004          13.7828348747865  153127606204.603  ...  223209533.911466    309047437
2005          13.7086097328953  186931152701.965  ...  97191584.4838922  125085422.6
2006          21.3902143492892  219487753605.769  ...  154593586.734786  128123730.4
2007          22.2111475246564  274935723329.914  ...  144518471.520768    134460312
2008          21.1014580679688  348111233135.201  ...  75505354.7471879  129425807.6
2009          18.2953229616244  316111747718.662  ...  821891029.988351  542317089.1
2010          17.3052805596303  411356488094.631  ...  731779021.646729  528729079.6
2011          17.3484303943707  521191523004.306  ...  659175718.235734  527094857.9
2012          16.0551647849633  535340215254.062  ...  574407706.177803  520124286.6
2013          14.9543621104664   552574859170.72  ...   474482653.44302    519341900
2014           15.752009923961  524192481552.148  ...  363346140.379277  486727497.2
2015          14.1426047002076  601142376256.018  ...  418149725.852928  463752752.4
2016          14.6381195257706  563328016065.645  ...  406731446.398736  455165191.5
2017          13.0762522929971  660678610172.255  ...  292098759.611638  482184792.8
2018          14.4241190515684  508686062989.856  ...  86434589.0794849  470895600.2
2019          15.7963628519449  422995834686.456  ...  150626737.889991  468198468.7
2020          17.8537791737235  358374943437.124  ...  31937527.4134395           ..

[32 rows x 5460 columns]

In [ ]:
sample = df.set_index(['Country name','Indicator']).stack().reset_index(level=2,drop=True).reset_index(name='Value')
sample

       Country name                             Indicator             Value
0         Argentina              Gross savings (% of GDP)  16.0433766574382
1         Argentina              Gross savings (% of GDP)  13.5618560304189
2         Argentina              Gross savings (% of GDP)  13.6516281676646
3         Argentina              Gross savings (% of GDP)  16.2505279122602
4         Argentina              Gross savings (% of GDP)  15.6483624533872
...             ...                                   ...               ...
234775     Zimbabwe  Use of IMF credit (DOD, current US$)                 0
234776     Zimbabwe  Use of IMF credit (DOD, current US$)                 0
234777     Zimbabwe  Use of IMF credit (DOD, current US$)                 0
234778     Zimbabwe  Use of IMF credit (DOD, current US$)                 0
234779     Zimbabwe  Use of IMF credit (DOD, current US$)                 0

[234780 rows x 3 columns]

In [ ]:
sample[sample['Country name'] == 'Argentina']

     Country name                             Indicator             Value
0       Argentina              Gross savings (% of GDP)  16.0433766574382
1       Argentina              Gross savings (% of GDP)  13.5618560304189
2       Argentina              Gross savings (% of GDP)  13.6516281676646
3       Argentina              Gross savings (% of GDP)  16.2505279122602
4       Argentina              Gross savings (% of GDP)  15.6483624533872
...           ...                                   ...               ...
1113    Argentina  Use of IMF credit (DOD, current US$)                 0
1114    Argentina  Use of IMF credit (DOD, current US$)                 0
1115    Argentina  Use of IMF credit (DOD, current US$)                 0
1116    Argentina  Use of IMF credit (DOD, current US$)                 0
1117    Argentina  Use of IMF credit (DOD, current US$)                 0

[1118 rows x 3 columns]

In [ ]:
sample['Indicator'].count()

234780

In [ ]:
sample['Indicator'].unique()

array(['Gross savings (% of GDP)',
       'Gross national expenditure (current US$)', 'GDP (current US$)',
       'GDP per capita (current US$)',
       'Stocks traded, total value (current US$)',
       'Adjusted net national income per capita (current US$)',
       'Changes in inventories (current US$)',
       'Current account balance (BoP, current US$)',
       'Exports of goods and services (current US$)',
       'External balance on goods and services (current US$)',
       'Foreign direct investment, net outflows (BoP, current US$)',
       'Imports of goods and services (current US$)',
       'Industry (including construction), value added (current US$)',
       'International tourism, receipts (current US$)',
       'Market capitalization of listed domestic companies (current US$)',
       'Personal remittances, received (current US$)',
       'Personal remittances, paid (current US$)',
       'Portfolio equity, net inflows (BoP, current US$)',
       'Portfolio investment, bonds (PPG + PNG) (NFL, current US$)',
       'Portfolio investment, net (BoP, current US$)',
       'Pump price for gasoline (US$ per liter)',
       'Service exports (BoP, current US$)',
       'Service imports (BoP, current US$)',
       'Total reserves (includes gold, current US$)',
       'Total reserves minus gold (current US$)',
       'Use of IMF credit (DOD, current US$)'], dtype=object)

In [ ]:
sample['Indicator'][:44]

0                     Gross savings (% of GDP)
1                     Gross savings (% of GDP)
2                     Gross savings (% of GDP)
3                     Gross savings (% of GDP)
4                     Gross savings (% of GDP)
5                     Gross savings (% of GDP)
6                     Gross savings (% of GDP)
7                     Gross savings (% of GDP)
8                     Gross savings (% of GDP)
9                     Gross savings (% of GDP)
10                    Gross savings (% of GDP)
11                    Gross savings (% of GDP)
12                    Gross savings (% of GDP)
13                    Gross savings (% of GDP)
14                    Gross savings (% of GDP)
15                    Gross savings (% of GDP)
16                    Gross savings (% of GDP)
17                    Gross savings (% of GDP)
18                    Gross savings (% of GDP)
19                    Gross savings (% of GDP)
20                    Gross savings (% of GDP)
21                    Gross savings (% of GDP)
22                    Gross savings (% of GDP)
23                    Gross savings (% of GDP)
24                    Gross savings (% of GDP)
25                    Gross savings (% of GDP)
26                    Gross savings (% of GDP)
27                    Gross savings (% of GDP)
28                    Gross savings (% of GDP)
29                    Gross savings (% of GDP)
30                    Gross savings (% of GDP)
31                    Gross savings (% of GDP)
32                    Gross savings (% of GDP)
33                    Gross savings (% of GDP)
34                    Gross savings (% of GDP)
35                    Gross savings (% of GDP)
36                    Gross savings (% of GDP)
37                    Gross savings (% of GDP)
38                    Gross savings (% of GDP)
39                    Gross savings (% of GDP)
40                    Gross savings (% of GDP)
41                    Gross savings (% of GDP)
42                    Gross savings (% of GDP)
43    Gross national expenditure (current US$)
Name: Indicator, dtype: object

In [ ]:
years = np.arange(1990,2021)
years2 = ["1990 target","2000 target","2008 target","2009 target","2010 target","2011 target","2012 target",
                "2013 target","2014 target","2015 target","2016 target","2017 target"]
years = years.tolist() + years2

In [ ]:
total_years = len(years) * sample['Indicator'].count()
total_years

10095540

In [ ]:
sample['Year'] = np.divmod(np.arange(len(sample)),31)[0]+1990
sample['Year']

0         1990
1         1990
2         1990
3         1990
4         1990
          ...
234775    9563
234776    9563
234777    9563
234778    9563
234779    9563
Name: Year, Length: 234780, dtype: int64

In [ ]:
sample.head()

  Country name                 Indicator             Value  Year
0    Argentina  Gross savings (% of GDP)  16.0433766574382  1990
1    Argentina  Gross savings (% of GDP)  13.5618560304189  1990
2    Argentina  Gross savings (% of GDP)  13.6516281676646  1990
3    Argentina  Gross savings (% of GDP)  16.2505279122602  1990
4    Argentina  Gross savings (% of GDP)  15.6483624533872  1990

In [ ]:
sample

       Country name  ...  Year
0         Argentina  ...  1990
1         Argentina  ...  1990
2         Argentina  ...  1990
3         Argentina  ...  1990
4         Argentina  ...  1990
...             ...  ...   ...
234775     Zimbabwe  ...  9563
234776     Zimbabwe  ...  9563
234777     Zimbabwe  ...  9563
234778     Zimbabwe  ...  9563
234779     Zimbabwe  ...  9563

[234780 rows x 4 columns]

In [ ]:
list_of_years = []

for x in np.arange(32):
  for x in years:
    list_of_years.append(x)

In [ ]:
len(list_of_years)

1376

In [ ]:
new_list = []

for x in years:
  new_list.append(x)

In [ ]:
new_list.append(years)

In [ ]:
len(new_list)

44

In [ ]:
years_list = np.repeat(years, 7574)

In [ ]:
len(years_list)

325682

In [ ]:
sample['Year'] = years_list

ValueError: ignored

In [ ]:
sample.head()

  Country name                 Indicator             Value  Year
0    Argentina  Gross savings (% of GDP)  16.0433766574382  1990
1    Argentina  Gross savings (% of GDP)  13.5618560304189  1990
2    Argentina  Gross savings (% of GDP)  13.6516281676646  1990
3    Argentina  Gross savings (% of GDP)  16.2505279122602  1990
4    Argentina  Gross savings (% of GDP)  15.6483624533872  1990

In [ ]:
sample.Year.unique()

array([1990, 1991, 1992, ..., 9561, 9562, 9563])

In [ ]:
for x in years:
  np.repeat(x, 10)
  print(x)

In [ ]:
years = years.tolist()

In [ ]:
n = 5460
years_list = years * n

In [ ]:
sample['Year'] = years_list

In [ ]:
sample.head()

  Country name                 Indicator             Value  Year
0    Argentina  Gross savings (% of GDP)  16.0433766574382  1990
1    Argentina  Gross savings (% of GDP)  13.5618560304189  1991
2    Argentina  Gross savings (% of GDP)  13.6516281676646  1992
3    Argentina  Gross savings (% of GDP)  16.2505279122602  1993
4    Argentina  Gross savings (% of GDP)  15.6483624533872  1994

In [ ]:
sample['Year'].unique()

array([1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000,
       2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020,
       '1990 target', '2000 target', '2008 target', '2009 target',
       '2010 target', '2011 target', '2012 target', '2013 target',
       '2014 target', '2015 target', '2016 target', '2017 target'],
      dtype=object)

In [ ]:
df_prueba = sample.copy()

In [ ]:
df_prueba

In [ ]:
df_prueba = df_prueba[['Country name','Year','Value','Indicator']]

In [ ]:
Country_and_Years = df_prueba[['Country name','Year']]
Country_and_Years

In [ ]:
# df_prueba.drop(['Country name','Year'], axis=1, inplace=True)

In [ ]:
df_prueba

In [ ]:
df_prueba.info()

In [ ]:
df_prueba[df_prueba['Value'] == '..']

In [ ]:
df_prueba['Value'] = df_prueba['Value'].replace('..',0)

In [ ]:
df_prueba['Value'] = df_prueba['Value'].astype(int)

In [ ]:
df_prueba

In [ ]:
pd.crosstab(df_prueba['Country name'],df_prueba.Indicator, values=df_prueba.Value,aggfunc=sum)

In [ ]:
df_prueba

In [ ]:
df_prueba = df_prueba[['Country name','Year','Indicator','Value']]

In [ ]:
df_prueba

In [ ]:
df_final = df_prueba.pivot_table(values='Value',index=['Country name','Year'], columns='Indicator').reset_index()

In [ ]:
df_final.head()

In [ ]:
df_final['Year'].unique()

In [ ]:
df_final.to_csv('ProyectoFinal.csv', index=False)

In [ ]:
df_final.iloc[0:50]

In [ ]:
df_final.to_csv('dfcondummies2.csv',index=False)

In [ ]:
metrics = pd.read_csv('/content/drive/MyDrive/IronHack/Data Analysis/Bootcamp/Proyecto Final/ProyectoFinal.csv')

In [ ]:
metrics

In [ ]:
df_final2 = pd.concat([metrics, dummies], sort=False)
df_final2

In [ ]:
df_final2.to_csv('dfcondummies.csv', index=False)

In [ ]:
dummies

In [ ]:
years

In [ ]:
dummies.transpose()

In [ ]:
dummies.set_index('Country name')

In [ ]:
df1.drop(['Series Name','Series Code','Country Code'], axis=1, inplace=True)

In [ ]:
dum_sample = df1.set_index(['Country Name']).stack().reset_index(level=1,drop=True).reset_index(name='Value')
dum_sample

In [ ]:
dum_sample[dum_sample['Country Name'] == 'Argentina']

In [ ]:
dum_years = ['1990',
 '2000',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017']

n2 = 214

dum_sample['Year'] = dum_years * n2

In [ ]:
dum_sample.rename(columns={'Country Name':'Country name'},inplace=True)
dum_sample

In [ ]:
dum_sample['Year'] = dum_sample['Year'].astype(int)

In [ ]:
dum_sample.info()

In [ ]:
metrics.info()

In [ ]:
df_test4 = pd.merge(metrics, dum_sample, on=['Country name','Year'])

In [ ]:
df_test4['Year'].unique()

In [ ]:
df_test4

In [ ]:
df_test4.to_csv('datasetbueno.csv', index=False)

In [ ]:
dummies = pd.read_csv('/content/drive/MyDrive/IronHack/Data Analysis/Bootcamp/Proyecto Final/Backups/dfcondummies.csv')

In [ ]:
dummies.head()

In [ ]:
sample.head()